diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=schannel
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
core.autocrlf=input
core.safecrlf=warn
user.name=Pablo Parente
user.email=pabloparente@gmail.com
remote.origin.url=https://github.com/palote/traffic-light-game.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.desarrollo.remote=origin
branch.desarrollo.vscode-merge-base=origin/master
branch.desarrollo.merge=refs/heads/desarrollo
branch.master.remote=origin
branch.master.merge=refs/heads/master
